kind: List
apiVersion: v1
items:

- kind: ImageStream
  apiVersion: v1
  metadata:
    labels:
      app: atmmovil
    name: atmmovil
  spec: {}

- kind: BuildConfig
  apiVersion: v1
  metadata:
    labels:
      app: atmmovil
    name: atmmovil
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: atmmovil:latest
    source:
      git:
        uri: https://github.com/mikeintoch/atmmovil-openshift.git
      type: Git
    strategy:
      dockerStrategy:
        env:
        - name: appname
          value: atm_movil-webclient
        - name: apppkg
          value: atm_movil-webclient-1.0-SNAPSHOT.war
        - name: dsName
          value: ds_atm_movil
        - name: dsDatabaseName
          value: test
        - name: datasourceTarget
          value: AdminServer
        - name: dsJNDIName
          value: jdbc/atm_movil
        - name: dsDriverName
          value: oracle.jdbc.OracleDriver
        - name: dsURL
          value: jdbc:oracle:thin:@//192.168.42.1:1521/xe
        - name: dsUserName
          value: UGATMMOVILADMIN
        - name: dsPassword
          value: redhat
        - name: dsTestQuery
          value: SQL ISVALID
        from:
          kind: DockerImage
          name: mikeintoch/rhel7-weblogic-domain:latest
      type: Docker
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
