kind: BuildConfig
metadata:
  name: atmmovil-pipeline
spec:
  source:
    git:
      uri: 'https://github.com/mikeintoch/atmmovil-openshift'
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
