apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "resource-limits" 
spec:
  limits:
    -
      type: "Pod"
      max:
        cpu: "2" 
        memory: "2Gi" 
      min:
        cpu: "200m" 
        memory: "1Gi" 
    -
      type: "Container"
      max:
        cpu: "2" 
        memory: "2Gi" 
      min:
        cpu: "100m" 
        memory: "1Gi" 
      default:
        cpu: "300m" 
        memory: "1Gi" 
      defaultRequest:
        cpu: "200m" 
        memory: "1Gi" 
      maxLimitRequestRatio:
        cpu: "10" 
